apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    listeners=PLAINTEXT://kafka-broker:9092,EXTERNAL://kafka-broker:19092
    advertised.listeners=PLAINTEXT://kafka-broker:9092,EXTERNAL://192.168.0.100:19092
    inter.broker.listener.name=PLAINTEXT
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
spec:
  ports:
    - name: external
      port: 19092
      targetPort: 19092
      protocol: TCP
    - name: internal
      port: 9092
      targetPort: 9092
      protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
      - env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 10.43.214.82:2181
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_LISTENERS
          value: EXTERNAL://0.0.0.0:19092,CLIENT://0.0.0.0:9092
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: CLIENT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: EXTERNAL://192.168.0.100:19092,CLIENT://kafka-broker:9092
        image: bitnami/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092
