grafana:
  env:
    GF_SERVER_ROOT_URL: https://k3s.local/grafana
    GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
  # username is 'admin'
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts: ['k3s.local']
    path: "/grafana(/|$)(.*)"
    tls:
    - secretName: tls-credential
      hosts:
      - k3s.local